/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include <string.h>
#include "graph/types.h"
#include "aclnn_decode_index_score.h"

#include "opdev/make_op_executor.h"
#include "opdev/op_dfx.h"
#include "opdev/op_executor.h"
#include "opdev/tensor_view_utils.h"
#include "opdev/op_def.h"
#include "opdev/op_log.h"
#include "opdev/shape_utils.h"
#include "opdev/common_types.h"
#include "opdev/data_type_utils.h"
#include "opdev/format_utils.h"

using namespace op;

#ifdef __cplusplus
extern "C" {
#endif

namespace {

// Auto-generated by the CANN build from the op def (aclnn_inner).
extern aclnnStatus aclnnInnerDecodeIndexScoreGetWorkspaceSize(
    const aclTensor *query, const aclTensor *indexKvCache, const aclTensor *blockTable,
    const aclTensor *seqLens, const aclTensor *globalSeqLens,
    int64_t decodeQueryLen, int64_t blockOffset, int64_t initBlocks, int64_t localBlocks,
    int64_t scoreBlockStride, int64_t numChunks,
    const aclTensor *scoreOut, uint64_t *workspaceSize, aclOpExecutor **executor);

extern aclnnStatus aclnnInnerDecodeIndexScore(void *workspace, uint64_t workspaceSize, aclOpExecutor *executor,
                                              const aclrtStream stream);

} // namespace

aclnnStatus aclnnDecodeIndexScoreGetWorkspaceSize(
    const aclTensor *query, const aclTensor *indexKvCache, const aclTensor *blockTable,
    const aclTensor *seqLens, const aclTensor *globalSeqLens,
    int64_t decodeQueryLen, int64_t blockOffset, int64_t initBlocks, int64_t localBlocks,
    int64_t scoreBlockStride, int64_t numChunks,
    const aclTensor *scoreOut, uint64_t *workspaceSize, aclOpExecutor **executor)
{
    if (query == nullptr || indexKvCache == nullptr || blockTable == nullptr || seqLens == nullptr ||
        globalSeqLens == nullptr || scoreOut == nullptr) {
        OP_LOGE(ACLNN_ERR_PARAM_NULLPTR, "Inputs or output of DecodeIndexScore is nullptr.");
        return ge::GRAPH_FAILED;
    }
    if (decodeQueryLen <= 0 || scoreBlockStride <= 0 || numChunks <= 0) {
        OP_LOGE(ACLNN_ERR_PARAM_INVALID, "decode_query_len/score_block_stride/num_chunks must be positive.");
        return ge::GRAPH_FAILED;
    }

    return aclnnInnerDecodeIndexScoreGetWorkspaceSize(
        query, indexKvCache, blockTable, seqLens, globalSeqLens,
        decodeQueryLen, blockOffset, initBlocks, localBlocks, scoreBlockStride, numChunks,
        scoreOut, workspaceSize, executor);
}

aclnnStatus aclnnDecodeIndexScore(void *workspace, uint64_t workspaceSize, aclOpExecutor *executor,
                                  const aclrtStream stream)
{
    return aclnnInnerDecodeIndexScore(workspace, workspaceSize, executor, stream);
}

#ifdef __cplusplus
}
#endif
